/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3dspline;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author Akash
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this.initComponents();
        this.surfaceDivSel.setValue(show.getWireframeDivision());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        wireframeSel = new javax.swing.JCheckBox();
        controlPointToggleSel = new javax.swing.JCheckBox();
        surfaceDivSel = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        rotateUp = new javax.swing.JButton();
        rotateRight = new javax.swing.JButton();
        rotateLeft = new javax.swing.JButton();
        rotateDown = new javax.swing.JButton();
        lightSourceToggleSel = new javax.swing.JCheckBox();
        shadeToggler = new javax.swing.JToggleButton();
        addLightSource = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        colorChooseButton = new javax.swing.JButton();
        lightMoveXup = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        moveLightXdown = new javax.swing.JButton();
        moveLightYdown = new javax.swing.JButton();
        lightMoveYup = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        moveLightZdown = new javax.swing.JButton();
        lightMoveZup = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        delLight = new javax.swing.JButton();
        show = new pkg3dspline.MainPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wireframeSel.setText("WireFrame");
        wireframeSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wireframeSelActionPerformed(evt);
            }
        });

        controlPointToggleSel.setText("Show Control Points");
        controlPointToggleSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlPointToggleSelActionPerformed(evt);
            }
        });

        surfaceDivSel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                surfaceDivSelStateChanged(evt);
            }
        });

        jLabel1.setText("Surface Divisions");

        rotateUp.setText("^");
        rotateUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateUpActionPerformed(evt);
            }
        });

        rotateRight.setText(">");
        rotateRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateRightActionPerformed(evt);
            }
        });

        rotateLeft.setText("<");
        rotateLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateLeftActionPerformed(evt);
            }
        });

        rotateDown.setText("v");
        rotateDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateDownActionPerformed(evt);
            }
        });

        lightSourceToggleSel.setText("Show Light Sources");
        lightSourceToggleSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightSourceToggleSelActionPerformed(evt);
            }
        });

        shadeToggler.setText("FlatShade");
        shadeToggler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shadeTogglerActionPerformed(evt);
            }
        });

        addLightSource.setText("Add LightSource");
        addLightSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLightSourceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wireframeSel)
                    .addComponent(lightSourceToggleSel)
                    .addComponent(controlPointToggleSel))
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(shadeToggler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(rotateLeft))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addLightSource)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rotateUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rotateRight)
                        .addGap(288, 288, 288)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(surfaceDivSel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rotateDown))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wireframeSel)
                            .addComponent(surfaceDivSel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(shadeToggler))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(controlPointToggleSel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lightSourceToggleSel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(addLightSource))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rotateUp)
                        .addGap(18, 18, 18)
                        .addComponent(rotateDown))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotateRight)
                            .addComponent(rotateLeft))))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", jPanel1);

        colorChooseButton.setText("ChooseColor");
        colorChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorChooseButtonActionPerformed(evt);
            }
        });

        lightMoveXup.setText("^");
        lightMoveXup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightMoveXupActionPerformed(evt);
            }
        });

        jLabel2.setText("Move X");

        moveLightXdown.setText("v");
        moveLightXdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveLightXdownActionPerformed(evt);
            }
        });

        moveLightYdown.setText("v");
        moveLightYdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveLightYdownActionPerformed(evt);
            }
        });

        lightMoveYup.setText("^");
        lightMoveYup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightMoveYupActionPerformed(evt);
            }
        });

        jLabel3.setText("Move Y");

        moveLightZdown.setText("v");
        moveLightZdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveLightZdownActionPerformed(evt);
            }
        });

        lightMoveZup.setText("^");
        lightMoveZup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightMoveZupActionPerformed(evt);
            }
        });

        jLabel4.setText("Move Z");

        delLight.setText("Delete Light");
        delLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delLightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel2)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel3)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(lightMoveXup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveLightXdown)
                        .addGap(45, 45, 45)
                        .addComponent(lightMoveYup)
                        .addGap(18, 18, 18)
                        .addComponent(moveLightYdown)
                        .addGap(57, 57, 57)
                        .addComponent(lightMoveZup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveLightZdown)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 459, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delLight)
                    .addComponent(colorChooseButton))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(colorChooseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lightMoveYup)
                    .addComponent(moveLightYdown)
                    .addComponent(lightMoveZup)
                    .addComponent(moveLightZdown)
                    .addComponent(lightMoveXup)
                    .addComponent(moveLightXdown)
                    .addComponent(delLight))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Light Source", jPanel2);

        javax.swing.GroupLayout showLayout = new javax.swing.GroupLayout(show);
        show.setLayout(showLayout);
        showLayout.setHorizontalGroup(
            showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        showLayout.setVerticalGroup(
            showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wireframeSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wireframeSelActionPerformed
        show.toggleWireframe();
    }//GEN-LAST:event_wireframeSelActionPerformed

    private void controlPointToggleSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlPointToggleSelActionPerformed
        show.toggleShowControl();
    }//GEN-LAST:event_controlPointToggleSelActionPerformed

    private void surfaceDivSelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_surfaceDivSelStateChanged
        int n = (Integer)this.surfaceDivSel.getValue();
        show.setWireframeDivision(n);
    }//GEN-LAST:event_surfaceDivSelStateChanged

    private void rotateUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateUpActionPerformed
        show.rotateX(10);
    }//GEN-LAST:event_rotateUpActionPerformed

    private void rotateDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateDownActionPerformed
        show.rotateX(-10);
    }//GEN-LAST:event_rotateDownActionPerformed

    private void rotateRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateRightActionPerformed
        show.rotateY(10);
    }//GEN-LAST:event_rotateRightActionPerformed

    private void rotateLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateLeftActionPerformed
        show.rotateY(-10);
    }//GEN-LAST:event_rotateLeftActionPerformed

    private void lightSourceToggleSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightSourceToggleSelActionPerformed
        show.toogleLight();
    }//GEN-LAST:event_lightSourceToggleSelActionPerformed

    private void shadeTogglerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shadeTogglerActionPerformed
        show.toggleShade();
        if(show.getShade())
            this.shadeToggler.setText("Gourard");
        else
            this.shadeToggler.setText("Flat");
    }//GEN-LAST:event_shadeTogglerActionPerformed

    private void colorChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorChooseButtonActionPerformed
        Color color = new Color(0,0,0);
        color = JColorChooser.showDialog(this,"Select Light Color",color);
        show.setLightColor(color);
    }//GEN-LAST:event_colorChooseButtonActionPerformed

    private void lightMoveXupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightMoveXupActionPerformed
        show.moveLightX(5);
    }//GEN-LAST:event_lightMoveXupActionPerformed

    private void moveLightXdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLightXdownActionPerformed
        show.moveLightX(-5);
    }//GEN-LAST:event_moveLightXdownActionPerformed

    private void moveLightYdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLightYdownActionPerformed
        show.moveLightY(5);
    }//GEN-LAST:event_moveLightYdownActionPerformed

    private void lightMoveYupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightMoveYupActionPerformed
        show.moveLightY(-5);
    }//GEN-LAST:event_lightMoveYupActionPerformed

    private void moveLightZdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLightZdownActionPerformed
        show.moveLightZ(-5);
    }//GEN-LAST:event_moveLightZdownActionPerformed

    private void lightMoveZupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightMoveZupActionPerformed
        show.moveLightZ(5);
    }//GEN-LAST:event_lightMoveZupActionPerformed

    private void addLightSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLightSourceActionPerformed
        show.newLight();
    }//GEN-LAST:event_addLightSourceActionPerformed

    private void delLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delLightActionPerformed
        show.delLight();
    }//GEN-LAST:event_delLightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLightSource;
    private javax.swing.JButton colorChooseButton;
    private javax.swing.JCheckBox controlPointToggleSel;
    private javax.swing.JButton delLight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton lightMoveXup;
    private javax.swing.JButton lightMoveYup;
    private javax.swing.JButton lightMoveZup;
    private javax.swing.JCheckBox lightSourceToggleSel;
    private javax.swing.JButton moveLightXdown;
    private javax.swing.JButton moveLightYdown;
    private javax.swing.JButton moveLightZdown;
    private javax.swing.JButton rotateDown;
    private javax.swing.JButton rotateLeft;
    private javax.swing.JButton rotateRight;
    private javax.swing.JButton rotateUp;
    private javax.swing.JToggleButton shadeToggler;
    private pkg3dspline.MainPanel show;
    private javax.swing.JSpinner surfaceDivSel;
    private javax.swing.JCheckBox wireframeSel;
    // End of variables declaration//GEN-END:variables
}
